# Generated by Django 5.2.8 on 2025-12-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='auth_tokes',
            new_name='auth_token',
        ),
    ]
