# Generated by Django 5.2.8 on 2025-12-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_auth_tokes_profile_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_verification_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
